version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv/app:cached
    environment:
      APP_ENV: dev
      DATABASE_URL: "pgsql://postgres:postgres@db:5432/character_vitae"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: character_vitae
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface web (accessible via localhost:8025)
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/srv/app:cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db-data:
